IMA_SET_PRICES_WITH = "Set Prices With";
IMA_CLEAR = "Clear";
IMA_IGORS_MASS_AUCTION = "Igor's Mass Auction";
IMA_MASS_AUCTION = "Igors!";
IMA_SENDINFO = "Are you sure you want to place these auctions? Total deposit will be:";
IMA_SENDINFO2 = "You are placing:";
IMA_ERROR = "An error occured in Igor's Mass Auction. Please submit a bug report wherever you got this mod";
IMA_ITEMS = "Item(s)";
IMA_POSTING_ITEM = "Posting item ";
IMA_OF = " of ";
IMA_DEFAULT = "Default";
IMA_VALUE_MULTIPLIER = "Value Multiplier";
IMA_ALL_SAME_PRICE = "All Same Price";
IMA_EASY_AUCTION = "EasyAuction";
IMA_AUCTIONEER_AUCTION = "Auctioneer";
IMA_AUCTIONEERUNDERCUT_AUCTION = "Auc-Undercut"
IMA_AUCTIONLITE_AUCTION = "AuctionLite"
IMA_START_PRICE = "Start Price";
IMA_BUYOUT_PRICE = "Buyout Price";
IMA_FOR = "for";
IMA_SET_ALL_PRICES = "Set All Prices";
IMA_MOUSEOVER_TEXT = "Drag or Alt+click items to add them";
IMA_HOLDALTTEXT = "One Click Auctions";
IMA_CLOSE = "Close";
IMA_SUBMIT = "Submit";
IMA_SET_START_PRICE = "Set Start Price x";
IMA_OF_BASE_PRICE = "of Base Price";
IMA_SET_BUYOUT = "Set Buyout x";
IMA_OF_START_PRICE = "of Start Price";
IMA_CANCEL = "Cancel";
IMA_ADD_ALL = "Auction everything"
IMA_QUERY_ALL = "Query bag items"


if ( GetLocale() == "esES" ) then
IMA_SET_PRICES_WITH = "Fijar precios con:";
IMA_CLEAR = "Limpiar";
IMA_IGORS_MASS_AUCTION = "Subasta Masiva de Igor - 2.7.2";
IMA_MASS_AUCTION = "Subasta Masiva";
IMA_SENDINFO = "Estas seguro de que quieres realizar estas subastas? El deposito total sera:";
IMA_SENDINFO2 = "Estas subastando:";
IMA_ERROR = "Ha ocurrido un error. Por favor, remite un informe a donde hallaste este AddOn";
IMA_ITEMS = "Objeto(s)";
IMA_POSTING_ITEM = "Objeto a subastar ";
IMA_OF = " de ";
IMA_DEFAULT = "Por defecto";
IMA_VALUE_MULTIPLIER = "Valor Multiplicador";
IMA_ALL_SAME_PRICE = "Todos el mismo precio";
IMA_EASY_AUCTION = "Subasta Facil";
IMA_START_PRICE = "Precio de salida";
IMA_BUYOUT_PRICE = "Precio de compra";
IMA_FOR = "para";
IMA_SET_ALL_PRICES = "Fijar precios";
IMA_MOUSEOVER_TEXT = "Arrastra o haz ALT+Click para anyadir objetos";
IMA_HOLDALTTEXT = "One Click Auctions";
IMA_CLOSE = "Cerrar";
IMA_SUBMIT = "Subastar";
IMA_SET_START_PRICE = "% Precio Salida";
IMA_OF_BASE_PRICE = "del Precio Base";
IMA_SET_BUYOUT = "% Precio Compra";
IMA_OF_START_PRICE = "del Precio Salida";
IMA_CANCEL = "Cancelar";
end

if ( GetLocale() == "zhTW" ) then
IMA_SET_PRICES_WITH = "設定價格為";
IMA_CLEAR = "清除";
IMA_IGORS_MASS_AUCTION = "批發助手 2.7.2";
IMA_MASS_AUCTION = "批發助手";
IMA_SENDINFO = "您確定要進行這些拍賣嗎？拍賣總金額為：";
IMA_SENDINFO2 = "您的設定：";
IMA_ERROR = "批發助手出現錯誤訊息，如可能的話，請回報給作者";
IMA_ITEMS = "物品";
IMA_POSTING_ITEM = "拍賣項目";
IMA_OF = " 屬於";
IMA_DEFAULT = "預設";
IMA_VALUE_MULTIPLIER = "拍賣價格";
IMA_ALL_SAME_PRICE = "相同價格";
IMA_EASY_AUCTION = "簡單販售";
IMA_START_PRICE = "開始拍賣";
IMA_BUYOUT_PRICE = "買斷價格";
IMA_FOR = "給";
IMA_SET_ALL_PRICES = "設定全部金額";
IMA_MOUSEOVER_TEXT = "使用 Alt 加滑鼠左鍵進行快速拍賣商品";
IMA_HOLDALTTEXT = "一鍵拍賣";
IMA_CLOSE = "關閉";
IMA_SUBMIT = "提交";
IMA_SET_START_PRICE = "設定初始價格 %";
IMA_OF_BASE_PRICE = "初始價格";
IMA_SET_BUYOUT = "設定直購金額 %";
IMA_OF_START_PRICE = "開始價格";
IMA_CANCEL = "取消";
end

if ( GetLocale() == "frFR" ) then
IMA_SET_PRICES_WITH = "Définir les prix avec";
IMA_CLEAR = "Nettoyer";
IMA_IGORS_MASS_AUCTION = "Igor's Mass Auction - Version 2.7.2";
IMA_MASS_AUCTION = "Vente en masse";
IMA_SENDINFO = "Etes vous sur de vouloir placer toutes ces ventes ? Le dépôt total sera de :";
IMA_SENDINFO2 = "Vous allez placer :";
IMA_ERROR = "Une erreur interne à Igor's Mass Auction est survenue. Si possible, soumettez un rapport d'erreur là où vous avez télécharger l'addon.";
IMA_ITEMS = "Objet(s)";
IMA_POSTING_ITEM = "Envoi de l'objet ";
IMA_OF = " de ";
IMA_DEFAULT = "Par défaut";
IMA_VALUE_MULTIPLIER = "Multiple de valeur";
IMA_ALL_SAME_PRICE = "Tous au même prix";
IMA_EASY_AUCTION = "EasyAuction";
IMA_START_PRICE = "Prix de départ";
IMA_BUYOUT_PRICE = "Prix achat direct";
IMA_FOR = "pour";
IMA_SET_ALL_PRICES = "Appliquer les prix";
IMA_MOUSEOVER_TEXT = "Faites glisser les objet ou effectuez un alt + clic dessus pour les ajouter";
IMA_HOLDALTTEXT = "Ventes en un clic";
IMA_CLOSE = "Fermer";
IMA_SUBMIT = "Envoyer";
IMA_SET_START_PRICE = "Prix de départ %";
IMA_OF_BASE_PRICE = "du prix de base";
IMA_SET_BUYOUT = "Prix achat direct %";
IMA_OF_START_PRICE = "du prix de départ";
IMA_CANCEL = "Annuler";
end